Controllers/HomePostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PetCommunity.Data;
using PetCommunity.Models;

namespace PetCommunity.Controllers
{
    public class HomePostController : Controller
    {
        private readonly ApplicationDbContext _context;

        public HomePostController(ApplicationDbContext context)
        {
            _context = context;
        }



        public IActionResult AllComments()
        {
            return PartialView(_context.comments.ToList());
        }

        //===============================================
        // GET: HomePost/Create
        public IActionResult CreateComment()
        {
            
            //ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            return PartialView();
        }

        // POST: HomePost/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateComment(Comment comment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(comment);
                await _context.SaveChangesAsync();
                //return RedirectToAction("Details");
                return RedirectToAction("Details", new { id = comment.PostId });
            }
            //ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id",comment.UserId);
            return RedirectToAction("Details", new { id = comment.PostId });
        }
        //===============================================
        // GET: HomePost
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Posts.Include(p => p.User);
            ViewBag.Post= await _context.Posts.ToListAsync();
            return View();
        }

        // GET: HomePost/Details/5
        public async Task<IActionResult> Details(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .Include(p => p.User).Include(c=>c.Comments)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }
            ViewData["numberOfcomments"]=_context.comments.ToList().Count();
            ViewBag.Post = post;
            return View();
        }

        // GET: HomePost/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: HomePost/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Content,Image,Specialization,Date,Source,IsActive,UserId")] Post post)
        {
            if (ModelState.IsValid)
            {
                _context.Add(post);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", post.UserId);
            return View(post);
        }

        // GET: HomePost/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts.FindAsync(id);
            if (post == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", post.UserId);
            return View(post);
        }

        // POST: HomePost/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Content,Image,Specialization,Date,Source,IsActive,UserId")] Post post)
        {
            if (id != post.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(post);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostExists(post.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", post.UserId);
            return View(post);
        }

        // GET: HomePost/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // POST: HomePost/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var post = await _context.Posts.FindAsync(id);
            _context.Posts.Remove(post);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PostExists(int id)
        {
            return _context.Posts.Any(e => e.Id == id);
        }
    }
}

Views/HomePost/AllComments.cshtml
@*@model IEnumerable<PetCommunity.Models.Comment>*@
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<div class="container">
    <h5 class="mb-5 alert-dismissable table table-info text-center">Numbers of comments : @ViewData["numberOfcomments"]</h5>
</div>
@foreach (var item in ViewBag.Post.Comments)
{
<div class="container">
    <div class="pt-5 mt-5">

        <ul class="comment-list">
            <li class="comment table-info">
                <div class="comment-body">
                    <div class="text-nowrap bd-highlight" style="width: 8rem;">
                        @item.Name :
                    </div>
                    <div class="text-nowrap bd-highlight" style="width: 8rem;">
                        @item.Content

                    </div>
                    <div class="text-nowrap bd-highlight" style="width: 8rem;">
                        @DateTime.Now
                    </div>
                    @*<h3 class="">@item.Name</h3>
                        <p>@item.Content</p>
                        <div class="meta">@DateTime.Now</div>*@
                </div>
            </li>
        </ul>
    </div>
</div>
}

Views/HomePost/CreateComment.cshtml
@model PetCommunity.Models.Comment
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
//Model.PostId = ViewBag.Post.Id;
}
<div class="container">
    <div class="comment-form-wrap pt-5">
        <h3 class="mb-5">Leave a comment</h3>
        @using (Html.BeginForm("CreateComment", "HomePost", FormMethod.Post))
        {
            <div class="container">
                <div class="form-group row">
                    @Html.LabelFor(c => c.Name, new { @class = "form-label" })
                    @Html.TextBoxFor(c => c.Name, new { @class = "form-control" })
                </div>
                <div class="form-group row">
                    @Html.LabelFor(c => c.Content, new { @class = "form-label", })
                    @Html.TextBoxFor(c => c.Content, new { @class = "form-control" })
                </div>
                <br />
            </div>

            <input type="hidden" asp-for="PostId" value="@ViewBag.Post.Id" />

            <button type="submit" class="btn bg-info">Create</button>
        }
    </div>
</div>

Views/HomePost/Details.cshtml
@*@model PetCommunity.Models.Post*@
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<section class="ftco-section ftco-degree-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 ftco-animate">
                <p>
                    <img src="/Uploads/@ViewBag.Post.ImageUrl" alt="" class="img-fluid" width="400" height="100">
                </p>
                <h2 class="mb-3">@ViewBag.Post.Date</h2>
                @*<p>@ViewBag.Post.user.FirstName</p>*@
                <p>@ViewBag.Post.Content</p>
            </div>
        </div>
    </div>
</section>

<partial name="AllComments" />
@*@Html.Partial("CreateComment", ViewBag.Post.Id)*@
@*@Html.Partial("_MyPartial", new
{
    Property1 = "Value1",
    Property2 = "Value2"
}.ToViewDataDictionary())*@
<partial name="CreateComment" />

@*<partial name="CreateComment" />*@

Views/HomePost/Index.cshtml
@*@model IEnumerable<PetCommunity.Models.Post>*@
@*@inject (PetCommunity.Models.Comment)*@
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}
<section class="hero-wrap hero-wrap-2" style="background-image: url('../images/bg_2.jpg');" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end">
            <div class="col-md-9 ftco-animate pb-5">
                <p class="breadcrumbs mb-2"><span class="mr-2"><a href="index.html">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>HomePost <i class="ion-ios-arrow-forward"></i></span></p>
                <h1 class="mb-0 bread">HomePost</h1>
            </div>
        </div>
    </div>
</section>


{


}
<section class="ftco-section bg-light">
    <div class="container">
        <div class="row d-flex">
            @foreach (var item in ViewBag.Post)
            {
                <div class="col-md-4 d-flex ftco-animate">
                    <div class="blog-entry align-self-stretch">
                        <a asp-action="Details" asp-route-id="@item.Id" class="block-20 rounded" style="background-image: url('../Uploads/@item.ImageUrl');">
                        </a>
                        <div class="text p-4">
                            <div class="meta mb-2">
                                <div><a href="#">@item.Date</a></div>
                                @*<div><a href="#">@item.User.FirstName</a></div>*@
                                <div><a href="#" class="meta-chat"><span class="fa fa-comment"></span>@item.Id</a></div>
                            </div>
                            <h3 class="heading"><a href="#">@item.Title</a></h3>
                            @*<a asp-action="Details" asp-route-id="@item.Id"><i class="fa fa-th-list" aria-hidden="true"></i></a>*@
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>